### ISSUE TITLE
0.3.8 breaks when diffing between an object and null value

### ISSUE THREAD

**Issue by leslc** [flitbit/diff#106]
Reporting an issue.

In 0.3.6, it was possible to diff an object against a null without throwing an error.  In 0.3.8, we get an error: 

"Cannot read property 'lhs' of undefined"
at deepDiff (deep-diff/index.js:156:76)

**Comment by fysidm** [comment]
Actually, it will crash when lhs or rhs is undefined and just in unix-based OS. Windows works fine. XD

**Comment by OliverJAsh** [comment]
Also happens when comparing with `undefined`:

```
TypeError: Cannot read property 'rhs' of undefined
```
