### ISSUE TITLE
question about the diff result structure

### ISSUE THREAD

**Issue by wqftowan** [flitbit/diff#119]
Hey @flitbit ,

I have one question about the diff result structure about kind of 'A' for V0.3.8. For instance, giving var lhs = {a: []}; var rhs = {a: [1]}; The diff result is with kind == 'A', index == 0, path == ["a"] and item == {kind: "N", rhs: 1}. I've no idea why it does not give the result with kind == 'N', path == ["a", 0], and rhs == 1? In this way there should be no need to maintain the 'A' kind for diff result, IMO it's much easier to be understood. Thanks.

**Comment by wqftowan** [comment]
@flitbit

**Comment by wqftowan** [comment]
![a](https://user-images.githubusercontent.com/8773370/32374512-0bea4c62-c0d9-11e7-8051-3d2eb4330e42.png)

**Comment by flitbit** [comment]
Ever since this became a to 1% NPM component I've tried to refrain from changing the structure of the diff result in order to not break the many many users of the library. You'll see I only changed it once.

Your suggestion seems logical.
