### ISSUE TITLE
duplicate path when diff array of object property

### ISSUE THREAD

**Issue by shenrenguo** [flitbit/diff#124]
left = { key: [ {A: **0**, B: 1}, {A: 2, B: 3} ] }
right = { key: [ {A: **9**, B: 1}, {A: 2, B: 3} ] }

r = diff(left, right)
only one changes occurred, but the output difference have 3:
{kind: 'E', path: ['key', 0, 'A'], lhs: 0, rhs: 9}
{kind: 'E', path: ['key.0', 'A'],  lhs: 0, rhs: 9}
{kind: 'E', path: ['key.0.A'],     lhs: 0, rhs: 9}

**Comment by flitbit** [comment]
Added a script that shows this is not an issue: look at [issue-124.js](https://github.com/flitbit/diff/blob/5907aa3392c63db9ee8324329e28a29cb43bc518/examples/issue-124.js)... if you still have issues, please tell me more about your environment, versions, etc.
