### ISSUE TITLE
Import deepDiff from 'deep-diff' using Rollup is wrong.

### ISSUE THREAD

**Issue by moersing** [flitbit/diff#128]
Hi, On the 1.0.0 version , I using `import deepDiff from 'deep-diff'` with Rollup,  But  I get an error : 
`Error: 'observableDiff' is not exported by node_modules/deep-diff/index.js`. 
I think this is a bug relative[#93](https://github.com/flitbit/diff/issues/92) , Because I found `index.es.js` file on the 0.3.8 version  but the 1.0.0 not, Why did you deleted it ?

**Comment by flitbit** [comment]
I deleted index.es.js because it was redundant and complicated dev on this module. Since I only visit it once in a while I wanted it simplified. Can I get a link to Rollup?

**Comment by flitbit** [comment]
nm, found it.

**Comment by flitbit** [comment]
Seems ok. Problem with what Rollup is doing?

Transcript:

```bash
im5k:flitbit phillip$ node --version
v8.11.1
im5k:flitbit phillip$ node
> const diff = require('deep-diff')
undefined
> diff.observableDiff
[Function: observableDiff]
> .exit
```
