### ISSUE TITLE
The DeepDiff.diff is coming out as undefined 

### ISSUE THREAD

**Issue by RsMandal** [flitbit/diff#132]
import  * as DeepDiff from 'deep-diff';

  static checkForChange(oldData: DdmForm, newData: DdmForm) {    
    var diffrence =  DeepDiff.diff(oldData, newData);     
    console.log(diffrence);
    return diffrence;
  }

I tested DeepDiff.diff with Runkit. it works fine there. But here the diffrence is always coming as undefined. though oldData and newData are not undefined

**Comment by fasiha** [comment]
Ran into the case where if `oldData` and `newData` are both exactly the same, `diff` returns `undefined`: in Runkit:
```js
var deepDiff = require("deep-diff")
console.log(deepDiff({b:94,a:10}, {b:94,a:10})) // undefined
```

**Comment by cerebralkungfu** [comment]
By design. Seemed reasonable at the time I wrote it. Breaking changes in v2.x (as time allows) will fix this to work more naturally.
