### ISSUE TITLE
Forked to fix #142

### ISSUE THREAD

**Issue by TSiege** [flitbit/diff#148]
I really like this project, but I ended up forking forking it to fix issue https://github.com/flitbit/diff/issues/142.  I ended up tweaking it to better suit my needs; however, I'd be happy to help tweak my changes so they can merged back into the main project. Here's my fork https://github.com/bustle/yajsondiff, it is now in typescript and has one dependency, but I'm sure we could work out a good solution if you're interested.

**Comment by flitbit** [comment]
See comments on #142
