### ISSUE TITLE
Having trouble understanding how the prefilter should work

### ISSUE THREAD

**Issue by tnrich** [flitbit/diff#34]
I am a little bit confused by the documentation of the pre-filter functionality. 

At one point in the readme, it says:
"Diff arguments:
```prefilter``` - an optional function that determines whether difference analysis should continue down the object graph."

And,
"Pre-filtering Object Properties
The prefilter's signature should be ```function(path, key)``` and it should return a truthy value for any path-key combination that should be filtered. If filtered, the difference analysis does no further analysis of on the identified object-property path."

But there is no actual instance of a diff that uses the pre-filter in the readme or examples that I could find. Something showing exactly how to use the following function would be great!
```
diff.diff(lhs, rhs, function (path, key) {
    //logic
    }
});
```

The only thing I could find was:
```
observableDiff(lhs, rhs, function (d) {
    // Apply all changes except those to the 'name' property...
    if (d.path.length !== 1 || d.path.join('.') !== 'name') {
        applyChange(lhs, rhs, d);
    }
});
```
Which isn't the ```diff.diff``` method for one, and doesn't take in two arguments for another. 

Awesome package and thanks!

**Comment by flitbit** [comment]
The readme could use some more detail.

[Take a look at the tests](https://github.com/flitbit/diff/blob/1bd7cfc7e94a6339568c14046e9eeb205d2a7b7c/test/tests.js#L180-183), a `prefilter` tests whether the item at the `path` and `key` should be filtered. Any _truthy_ result will cause `diff` to filter the item.

There are several examples in the tests.

The `observableDiff` function is an underlying function, the 3rd param is the `observer` which is called for each _difference_ detected. [If you want to call `observableDiff`, the 4th parameter is the `prefilter`](https://github.com/flitbit/diff/blob/1bd7cfc7e94a6339568c14046e9eeb205d2a7b7c/index.js#L82).

**Comment by tnrich** [comment]
Awesome, thanks for the feedback. I took a look at the test and it cleared
up using a prefilter with a key. I'll investigate using a prefilter with a
path too since that's the actual operation I want to do.

Cheers,
Thomas
