### ISSUE TITLE
Deleting Array elements

### ISSUE THREAD

**Issue by MrMojoRisin49** [flitbit/diff#47]
Not sure but I think I've run into an issue dealing with deleting array elements. For example:

oldArray: [thing1, thing2, thing3, thing4]
newArray: [thing1, thing2]

I apply the diff using this code:

diff.observableDiff(oldArray, newArray, function (d) {
     diff.applyChange(oldArray, newArray, d);
});

And I expect:

oldArray: [thing1, thing2]

But I get:

oldArray: [thing1, thing2, thing4]

Not sure why this is. Is this an issue with my code or yours. Any help is greatly appreciated. Thanks in advance.

**Comment by jonathan-reisdorf** [comment]
Same issue here. I guess if you just loop through the diff and apply the changes one by one, the former index 3 will be index 2 after the deletion of thing3. The next applyChange then triggers a delete on thing4, which is recorded to be index 3, but now there is no index 3, so nothing happens.

**Comment by jonathan-reisdorf** [comment]
For a workaround see here:
https://github.com/flitbit/diff/issues/35

**Comment by ilovett** [comment]
I am also seeing this issue where the index seems to be changed and the diff index is no longer accurate...  The workaround mentioned by @jonathan-reisdorf in #35 is to call `reverse()` on your array of changes...

```
deep.diff(lhs, rhs).reverse().forEach(function(diffItem) {
  deep.applyChange(lhs, true, diffItem);
});
```

The default behaviour of `deep-diff` should be to provide the diffs of arrays already reversed.

**Comment by postrational** [comment]
+1 Same issue. Can the `observableDiff` function be changed to apply changes in reversed order in the library?
