### ISSUE TITLE
No revertDiff functionality

### ISSUE THREAD

**Issue by rcijvat** [flitbit/diff#51]
First of all, awesome diffing library! I use it for undo/redo management of objects. However, I am missing a revertDiff function that does exactly the opposite of applyDiff:

b === applyDiff(a, diff(a, b))
a === revertDiff(b, diff(a, b))

The only way to add this functionality is to alter the library, since the deepDiff (not exposed to the outside) function needs to be called. Before I start fiddling in the module code, I was wondering if there was a good reason that this functionality is not there yet, and if there might be something that I am overlooking.

**Comment by rcijvat** [comment]
Figured out that the API was not quite what I expected it to be. Possible improvement:
1) Clarify in docs that you do not need to provide the actual diff object to applyDiff. I expected that applyDiff applied a precomputed diff to a given object, hence my quest for the revertDiff function.
2) Documentation on the arguments and return values of the API would have helped me a great deal to quickly grab the meaning of these functions.
3) Remove the need to provide a source argument to both the revertChange and applyChange function. The arguments are not used, and are confusing. After all, we just want to apply/revert a change to an object.

After having these things clarified for myself, the lib works great! Thanks for all of your efforts!

**Comment by flitbit** [comment]
Thanks for the feedback; I'll try to update the docs.
