### ISSUE TITLE
Bower "no tag found that was able to satisfy 0.3.3"

### ISSUE THREAD

**Issue by rmckeel** [flitbit/diff#55]
It looks like the tag 0.3.3 needs to be added in order for bower to install the newest version properly.

    bower update deep-diff
    bower deep-diff#0.3.3       not-cached git://github.com/flitbit/diff.git#0.3.3
    bower deep-diff#0.3.3          resolve git://github.com/flitbit/diff.git#0.3.3
    bower deep-diff#0.3.3     ENORESTARGET No tag found that was able to satisfy 0.3.3

    Additional error details:
    Available versions in git://github.com/flitbit/diff.git: 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.7, 0.1.6, 0.1.4, 0.1.3, 0.1.2, 0.1.1

In the meantime before this tag is added, you can use this to install 0.3.3.

    bower i "git@github.com:flitbit/diff.git#619f6606ecef4098c4259db48387bebe68840ea" --save

Can a contributor add this tag?  Thanks!

  Ryan

**Comment by flitbit** [comment]
Damn; guess I be amateurish! Sorry - Done.

**Comment by rmckeel** [comment]
Amateurish?  No.  Deep-diff rocks and does a good amount of heavy lifting in our app.  Thanks for writing it!
