### ISSUE TITLE
Is the second argument (source) of applyChange superfluous?

### ISSUE THREAD

**Issue by jay3sh** [flitbit/diff#64]
From the interface point of view the `applyChange` function should not require the source object used while taking the diff. Therefore I found it confusing when I was trying it. I found that passing the second argument as empty object did not change the behavior. So when I looked into the code, the source argument is indeed not being used anywhere (except the check).

https://github.com/flitbit/diff/blob/master/index.js#L248-L272

Do you plan to remove it in future? It's important to know this because in my use case I compute the diff, save it to persistent storage and in future apply it on an object to get the original object. i.e. I don't have the source object in that scenario.
Thanks.

**Comment by flitbit** [comment]
Indeed, `source` appears to be unused... I even recall using `true` as arg 2 a time or two... it smells, I know.

The intent, which is probably obsolete, was to provide another seam/callback by which the caller could do more sophisticated analysis of the change based on the origin &mdash; but that work never made it out of my brain cavity into the module.

**Comment by aryeharmon** [comment]
still an issue.
