### ISSUE TITLE
Apply a diff?

### ISSUE THREAD

**Issue by rymoore** [flitbit/diff#65]
Is it possible to apply the results of a `diff` to an object? 

for example:

```
var myDiff = diff(jsonA, jsonB);
applyDiff(myDiff, jsonBcopy); // this is what I am wondering
```

I know it _appears_ unnecessary to do this, but I am comparing local files, then applying changes on a server to avoid excessively large file transfers.

**Comment by flitbit** [comment]
Examples are in [examples/apply-diff-from-any.js](https://github.com/flitbit/diff/blob/master/examples/apply-diff-from-any.js) and [examples/performance.js](https://github.com/flitbit/diff/blob/master/examples/performance.js#L33-L35)...

Essentially, if you have an array of differences, you can iteratively apply them to any object.

**Comment by chrismllr** [comment]
Similarly, Is there a way to copy a diff onto an empty object? Currently trying to generate a patch of only changed properties.

observableDIff/ applyChange is getting me as far as top-level fields, but if there are arrays involved it will break (as the empty patch object does not have an array)

error occurs at line 268
```
arr[index] = change.rhs;
```

my current use case:
```
const patch = {};

observableDiff(lhs, rhs, (d) => {
  applyChange(patch, rhs, d);
});

return patch;
```
