### ISSUE TITLE
get list of changed items?

### ISSUE THREAD

**Issue by FezVrasta** [flitbit/diff#68]
Hi,

I need to get just a simple list of the items that have been changed or added in an array, without any other information.

```
A = [ {a: 1}, {a: 2} ]
B = [ {a: 3}, {a: 2} ]

=> [ {a: 3} ]
```

How can I achieve it?

**Comment by sh977218** [comment]
you can use lodash difference achieve it.
https://lodash.com/docs/4.17.10#difference

**Comment by Berkmann18** [comment]
^ Or you could use this:
```js
const diff = arr => arr.reduce((a, b) => a.filter(c => !b.includes(c)))
```
Taken from [here](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_difference):
> ```js
>let arrays = [[1, 2, 3, 4, 5], [5, 2, 10]];
>console.log(arrays.reduce((a, b) => a.filter(c => !b.includes(c))));
>// output: [1, 3, 4]
>```
