### ISSUE TITLE
DeepDiff({ foo : undefined }, {}) reports no differences

### ISSUE THREAD

**Issue by matsbryntse** [flitbit/diff#70]
`DeepDiff({ foo : undefined }, {})` should report differences correctly

**Comment by bitliner** [comment]
+1

**Comment by lrdevries** [comment]
With the fix,

`
var left = {foo: undefined};
var right = {foo: undefined};

console.log(deepDiff.diff(left, right));
`

Does also triggers a deletion, even through they are simular.

**Comment by YacheLee** [comment]
I am afraid that this bug still exist when being in the linux-based environment.

**Comment by fysidm** [comment]
@YacheLee same situation here.
