### ISSUE TITLE
Array order?

### ISSUE THREAD

**Issue by trusktr** [flitbit/diff#72]
Based on the README

> Changes to arrays are recorded simplistically. We care most about the shape of the structure; therefore we don't take the time to determine if an object moved from one slot in the array to another.

In other words, if a diff removes an object, and then we undo that diff, could the array order not be the same?

**Comment by flitbit** [comment]
There is a supplied `revertChange` function - it restores the original structure, including restoring array order. I [added an example](https://github.com/flitbit/diff/blob/e54b00053324c4773e65c36557d6742f066ad38a/examples/issue-72.js) illustrating how it is used.
