### ISSUE TITLE
TypeError: changes is not a function

### ISSUE THREAD

**Issue by dskvr** [flitbit/diff#77]
Running Node v6 on Ubuntu 14.04 LTS. Figured this may have been an issue with newest release not being pushed to NPM, but I used a git dependency and referenced the newest release, got the same error. Upon looking at the code, I cannot say I understand what is attempting to be done here, or why `changes` is referenced as a function at any point. 

_Line 140_
`function deepDiff(lhs, rhs, changes, prefilter, path, key, stack) {` 

Line _192_
`changes(new DiffArray(currentPath, i, new DiffNew(undefined, rhs[i++])));`

Then, it appears to be self-referencial and recursively looping, which makes sense considering the nature of this module. However, I fail to see where or how `changes` is a function.

I'm at a loss on this one, I always prefer to try and figure these kinds of things out on my own, but I've read and re-read documentation, and the code has me flummoxed  :(

```
Diff Running
/vagrant/node_modules/deep-diff/index.js:192
            changes(new DiffArray(currentPath, i, new DiffNew(undefined, rhs[i++])));
            ^

TypeError: changes is not a function
    at deepDiff (/vagrant/node_modules/deep-diff/index.js:192:13)
    at blocks_analyze_diff (/vagrant/app.js:214:18)
    at Timeout.worker_block_content_analyze [as _repeat] (/vagrant/app.js:182:3)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by flitbit** [comment]
Definitely self-referencing and recursive. Starting on [index.es.js line 202](https://github.com/flitbit/diff/blob/5d6df249f02bb512bc8c86c6936bcd3690a469b5/index.es.js#L202-L208) illustrates how `changes` is used. It's pretty fundamental, it is essentially an _observer_. All changes are reported to the specified function. In fact, `accumulateDiff`, while serving as the **main** function of the entire library is also a pattern. I've used several alternate implementations, using different observers as necessary.

If there is indeed a bug, as you suggest, please report it with code that causes the bug to exhibit.
