### ISSUE TITLE
Unexpected results!

### ISSUE THREAD

**Issue by ketansp** [flitbit/diff#87]
I am trying to implement this library in my project, but I do not get expected results. Herewith sharing a sample of the data for your understanding

lhs
`{ region: 'string',
  state: 'string',
  country: 'string',
  mdmId: null,
  isActive: true,
  createdDate: '2017-01-07T07:30:47.000Z',
  lastModifiedDate: '2017-01-07T07:37:39.075Z',
  id: 14 }`

rhs
`{ region: 'string',
  state: 'string',
  country: 'string',
  mdmId: null,
  isActive: true,
  createdDate: 2017-01-07T07:30:47.000Z,
  lastModifiedDate: 2017-01-07T07:39:02.072Z,
  id: 14 }`

diff
`[ DiffDeleted { kind: 'D', path: [ 'region' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'state' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'country' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'mdmId' ], lhs: null },
  DiffDeleted { kind: 'D', path: [ 'isActive' ], lhs: true },
  DiffDeleted {
    kind: 'D',
    path: [ 'createdDate' ],
    lhs: '2017-01-07T07:30:47.000Z' },
  DiffDeleted {
    kind: 'D',
    path: [ 'lastModifiedDate' ],
    lhs: '2017-01-07T07:37:39.075Z' },
  DiffDeleted { kind: 'D', path: [ 'id' ], lhs: 14 },
  DiffNew { kind: 'N', path: [ '__cachedRelations' ], rhs: {} },
  DiffNew {
    kind: 'N',
    path: [ '__data' ],
    rhs:
     { region: 'string',
       state: 'string',
       country: 'string',
       mdmId: null,
       isActive: true,
       createdDate: 2017-01-07T07:30:47.000Z,
       lastModifiedDate: 2017-01-07T07:39:02.072Z,
       id: 14 } },
  DiffNew { kind: 'N', path: [ '__strict' ], rhs: false },
  DiffNew { kind: 'N', path: [ '__persisted' ], rhs: true } ]`

Am I missing out on something?

**Comment by DingoEatingFuzz** [comment]
Formatting this a little better you get this, which tells a story:

```js
[
  DiffDeleted { kind: 'D', path: [ 'region' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'state' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'country' ], lhs: 'string' },
  DiffDeleted { kind: 'D', path: [ 'mdmId' ], lhs: null },
  DiffDeleted { kind: 'D', path: [ 'isActive' ], lhs: true },
  DiffDeleted { kind: 'D', path: [ 'createdDate' ], lhs: '2017-01-07T07:30:47.000Z' },
  DiffDeleted { kind: 'D', path: [ 'lastModifiedDate' ], lhs: '2017-01-07T07:37:39.075Z' },
  DiffDeleted { kind: 'D', path: [ 'id' ], lhs: 14 },
  
  DiffNew { kind: 'N', path: [ '__cachedRelations' ], rhs: {} },
  DiffNew { kind: 'N', path: [ '__data' ], rhs: {
    region: 'string',
    state: 'string',
    country: 'string',
    mdmId: null,
    isActive: true,
    createdDate: '2017-01-07T07:30:47.000Z',
    lastModifiedDate: '2017-01-07T07:39:02.072Z',
    id: 14 
  } },
  DiffNew { kind: 'N', path: [ '__strict' ], rhs: false },
  DiffNew { kind: 'N', path: [ '__persisted' ], rhs: true }
]
```

Looks like you are diffing an object and a wrapper object.

**Comment by flitbit** [comment]
[Take a look at the tests, there is a `prefilter` option](https://github.com/flitbit/diff/blob/1bd7cfc7e94a6339568c14046e9eeb205d2a7b7c/test/tests.js#L180-183) that helps you ignore the _state-keeping_ features of your chosen framework.

Also, reference [issue #34](https://github.com/flitbit/diff/issues/34) which dealt with the same.
