### ISSUE TITLE
Change module system of the main file

### ISSUE THREAD

**Issue by thiamsantos** [flitbit/diff#92]
I'm trying to [use rollup as build tool for redux-logger](evgenyrodionov/redux-logger#225) following the example of what [react did](https://github.com/facebook/react/pull/9327). But I'm encountering a problem: rollup doesn't work well with umd builds(because it works with es2015 modules) and the only file exported by this [project is an umd](https://github.com/flitbit/diff/blob/master/index.js). So, I would like to send a PR to solve this problem.

For more info about why to use rollup you can read [Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c) that explain the main reasons why rollup is better for redux-logger.

Thanks for your time :wink:

**Comment by flitbit** [comment]
Completed with v0.3.5 &mdash; thanks @thiamsantos !
