### ISSUE TITLE
DeepDiff({ foo: undefined }, { foo: undefined }) reports a difference

### ISSUE THREAD

**Issue by tylercallahan** [flitbit/diff#98]
This behavior changed in v0.3.6 (likely [this commit](https://github.com/flitbit/diff/commit/af9930490d7c9dd5943ab8218faa80edbfaa4f6a)).

`DeepDiff({ foo: undefined }, { foo: undefined })`

returns:
0.3.5: `undefined`
0.3.6: `[{"kind":"D","path":["foo"]}]`

Expected: I believe this should not report a difference.

**Comment by flitbit** [comment]
Do you care to take a shot at a PR?

[At or around line 150](https://github.com/flitbit/diff/blob/f16f633d4a6712daaefa49ec82dc3ccb10aea472/index.es.js#L150) there needs to be a test to see if `key` is defined on the right-hand-side: `rhs.hasOwnProperty(key)`... or something like that.

A regression test in [test.js](https://github.com/flitbit/diff/blob/f16f633d4a6712daaefa49ec82dc3ccb10aea472/test/tests.js) would be nice too.

If you don't have time to contribute, I'll get to it soon.

**Comment by sberan** [comment]
🌤  ▶️ I have a PR here: https://github.com/flitbit/diff/pull/99

**Comment by flitbit** [comment]
Fixed with PR #99
